services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./files:/data
    depends_on:
      - synapse-db

  synapse-db:
    image: docker.io/postgres:17-alpine
    container_name: synapse-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=synapse_db
      - POSTGRES_USER=YOUR_POSTGRESDB_USER
      - POSTGRES_PASSWORD=YOUR_POSTGRESDB_USER_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./synapse-schemas:/var/lib/postgresql/data

  app-db:
    image: docker.io/postgres:17-alpine
    container_name: app-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=YOUR_POSTGRESDB_USER
      - POSTGRES_PASSWORD=YOUR_POSTGRESDB_USER_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./app-schemas:/var/lib/postgresql/data

  app-db-bouncer:
    image: edoburu/pgbouncer:latest
    container_name: app_db_bouncer
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://YOUR_POSTGRESDB_USER:YOUR_POSTGRESDB_USER_PASSWORD@app-db:5432/app_db
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
    ports:
      - "6432:5432"
    depends_on:
      - app-db

  caddy:
    image: docker.io/caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - synapse
    ports:
      - "8080:8080"
